# Generated by Django 4.2.21 on 2025-06-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
